@include('layouts.main.header')
@include('layouts.main.main')
@include('layouts.main.about')
@include('layouts.main.vision')
@include('layouts.main.goals')
@include('layouts.main.members')
@include('layouts.main.clients')
@include('layouts.main.jobs',['jobs' => $jobs])
@include('layouts.main.contact')
@include('layouts.main.branches')
@include('layouts.main.footer')